baseurl = "https://hellocodeblog.com"
title = "hello {code} blog"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the MIT license."
publishDir = "docs"

[author]
    name = "Philipp Badenhoop"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "// The computer science blog."
  Author = "Philipp Badenhoop"
  email = "philipp.badenhoop@hellocodeblog.com"
  Ganalytics = "XX-00000000-0"
  # This will load all the CSS defined in the list
  # customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/PBadenhoop"
[[params.social]]
    title = "github"
    url = "https://github.com/humboldtux"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -190