baseurl = "https://hellocodeblog.com"
title = "hello {code} blog"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "© 2019 by Philipp Badenhoop. All Rights Reserved."
publishDir = "docs"
pygmentsStyle = "paraiso-dark"
googleAnalytics = "UA-131477483-1"

[author]
  name = "Philipp Badenhoop"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "// The computer science blog."
  Author = "Philipp Badenhoop"
  email = "philipp.badenhoop@hellocodeblog.com"
  # This will load all the CSS defined in the list
  # customCSS = ["hello-code-blog.css"]

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/PBadenhoop"
[[params.social]]
  title = "github"
  url = "https://github.com/Badenhoop"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archive"
  url = "/post/"
  weight = -190

[taxonomies]
  tag = "tags"
  category = "categories"